Nethunter-Rootless-Fixed

diff --git a/Nethunter-Rootless-Fixed b/Nethunter-Rootless-Fixed
--- a/Nethunter-Rootless-Fixed
+++ b/Nethunter-Rootless-Fixed
@@ -1,7 +1,10 @@
 #!/data/data/com.termux/files/usr/bin/bash -e
 
-VERSION=2020011601
-BASE_URL=https://kali.download/nethunter-images/kali-2024.4/rootfs/kali-nethunter-rootfs-full-amd64.tar.xz
+VERSION=2024091801
+BASE_URL=https://image-nethunter.kali.org/nethunter-fs/kali-daily
+USERNAME=kali
+
+
 
 function unsupported_arch() {
     printf "${red}"
@@ -60,9 +63,49 @@ function get_arch() {
 }
 
 function set_strings() {
+    echo \
+    && echo "" 
+    ####
+    if [[ ${SYS_ARCH} == "arm64" ]];
+    then
+        echo "[1] NetHunter ARM64 (full)"
+        echo "[2] NetHunter ARM64 (minimal)"
+        echo "[3] NetHunter ARM64 (nano)"
+        read -p "Enter the image you want to install: " wimg
+        if (( $wimg == "1" ));
+        then
+            wimg="full"
+        elif (( $wimg == "2" ));
+        then
+            wimg="minimal"
+        elif (( $wimg == "3" ));
+        then
+            wimg="nano"
+        else
+            wimg="full"
+        fi
+    elif [[ ${SYS_ARCH} == "armhf" ]];
+    then
+        echo "[1] NetHunter ARMhf (full)"
+        echo "[2] NetHunter ARMhf (minimal)"
+        echo "[3] NetHunter ARMhf (nano)"
+        read -p "Enter the image you want to install: " wimg
+        if [[ "$wimg" == "1" ]]; then
+            wimg="full"
+        elif [[ "$wimg" == "2" ]]; then
+            wimg="minimal"
+        elif [[ "$wimg" == "3" ]]; then
+            wimg="nano"
+        else
+            wimg="full"
+        fi
+    fi
+    ####
+
+
     CHROOT=kali-${SYS_ARCH}
-    IMAGE_NAME=kalifs-${SYS_ARCH}-full.tar.xz
-    SHA_NAME=kalifs-${SYS_ARCH}-full.sha512sum
+    IMAGE_NAME=kali-nethunter-daily-dev-rootfs-${wimg}-${SYS_ARCH}.tar.xz
+    SHA_NAME=${IMAGE_NAME}.sha512sum
 }    
 
 function prepare_fs() {
@@ -77,14 +120,14 @@ function prepare_fs() {
 } 
 
 function cleanup() {
-    if [ -f ${IMAGE_NAME} ]; then
+    if [ -f "${IMAGE_NAME}" ]; then
         if ask "Delete downloaded rootfs file?" "N"; then
-	    if [ -f ${IMAGE_NAME} ]; then
-                rm -f ${IMAGE_NAME}
-	    fi
-	    if [ -f ${SHA_NAME} ]; then
-                rm -f ${SHA_NAME}
-	    fi
+        if [ -f "${IMAGE_NAME}" ]; then
+                rm -f "${IMAGE_NAME}"
+        fi
+        if [ -f "${SHA_NAME}" ]; then
+                rm -f "${SHA_NAME}"
+        fi
         fi
     fi
 } 
@@ -95,19 +138,20 @@ function check_dependencies() {
     ##apt update -y &> /dev/null
     apt-get update -y &> /dev/null || apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" dist-upgrade -y &> /dev/null
 
-    for i in proot tar axel wget; do
-        if [ -e $PREFIX/bin/$i ]; then
+    for i in proot tar axel; do
+        if [ -e "$PREFIX"/bin/$i ]; then
             echo "  $i is OK"
         else
             printf "Installing ${i}...\n"
             apt install -y $i || {
                 printf "${red}ERROR: Failed to install packages.\n Exiting.\n${reset}"
-	        exit
+            exit
             }
         fi
     done
     apt upgrade -y
 }
+
 
 function get_url() {
     ROOTFS_URL="${BASE_URL}/${IMAGE_NAME}"
@@ -116,9 +160,9 @@ function get_url() {
 
 function get_rootfs() {
     unset KEEP_IMAGE
-    if [ -f ${IMAGE_NAME} ]; then
+    if [ -f "${IMAGE_NAME}" ]; then
         if ask "Existing image file found. Delete and download a new one?" "N"; then
-            rm -f ${IMAGE_NAME}
+            rm -f "${IMAGE_NAME}"
         else
             printf "${yellow}[!] Using existing rootfs archive${reset}\n"
             KEEP_IMAGE=1
@@ -127,43 +171,62 @@ function get_rootfs() {
     fi
     printf "${blue}[*] Downloading rootfs...${reset}\n\n"
     get_url
-    wget ${EXTRA_ARGS} --continue "${ROOTFS_URL}"
+    wget --continue "${ROOTFS_URL}"
+}
+
+function check_sha_url() {
+    if ! curl --head --silent --fail "${SHA_URL}" > /dev/null; then
+        echo "[!] SHA_URL does not exist or is unreachable"
+        return 1
+    fi
+    return 0
+}
+
+function verify_sha() {
+    if [ -z $KEEP_IMAGE ]; then
+        printf "\n${blue}[*] Verifying integrity of rootfs...${reset}\n\n"
+        if [ -f "${SHA_NAME}" ]; then
+            sha512sum -c "$SHA_NAME" || {
+                printf "${red} Rootfs corrupted. Please run this installer again or download the file manually\n${reset}"
+                exit 1
+            }
+        else
+            echo "[!] SHA file not found. Skipping verification..."    
+        fi    
+    fi
 }
 
 function get_sha() {
     if [ -z $KEEP_IMAGE ]; then
         printf "\n${blue}[*] Getting SHA ... ${reset}\n\n"
         get_url
-        if [ -f ${SHA_NAME} ]; then
-            rm -f ${SHA_NAME}
+        if [ -f "${SHA_NAME}" ]; then
+            rm -f "${SHA_NAME}"
+        fi        
+        if check_sha_url; then
+            echo "[+] SHA_URL exists. Proceeding with download..."
+            wget --continue "${SHA_URL}"
+            verify_sha
+        else
+            echo "[!] SHA_URL does not exist. Skipping download."
         fi
-        wget ${EXTRA_ARGS} --continue "${SHA_URL}"
-    fi
-}
-
-function verify_sha() {
-    if [ -z $KEEP_IMAGE ]; then
-        printf "\n${blue}[*] Verifying integrity of rootfs...${reset}\n\n"
-        sha512sum -c $SHA_NAME || {
-            printf "${red} Rootfs corrupted. Please run this installer again or download the file manually\n${reset}"
-            exit 1
-        }
-    fi
+    fi        
 }
 
 function extract_rootfs() {
     if [ -z $KEEP_CHROOT ]; then
         printf "\n${blue}[*] Extracting rootfs... ${reset}\n\n"
-        proot --link2symlink tar -xf $IMAGE_NAME 2> /dev/null || :
+        proot --link2symlink tar -xf "$IMAGE_NAME" 2> /dev/null || :
     else        
         printf "${yellow}[!] Using existing rootfs directory${reset}\n"
     fi
 }
 
+
 function create_launcher() {
     NH_LAUNCHER=${PREFIX}/bin/nethunter
     NH_SHORTCUT=${PREFIX}/bin/nh
-    cat > $NH_LAUNCHER <<- EOF
+    cat > "$NH_LAUNCHER" <<- EOF
 #!/data/data/com.termux/files/usr/bin/bash -e
 cd \${HOME}
 ## termux-exec sets LD_PRELOAD so let's unset it before continuing
@@ -200,6 +263,7 @@ cmdline="proot \\
         -r $CHROOT \\
         -b /dev \\
         -b /proc \\
+        -b /sdcard \\
         -b $CHROOT\$home:/dev/shm \\
         -w \$home \\
            /usr/bin/env -i \\
@@ -217,16 +281,21 @@ else
 fi
 EOF
 
-    chmod 700 $NH_LAUNCHER
-    if [ -L ${NH_SHORTCUT} ]; then
-        rm -f ${NH_SHORTCUT}
+    chmod 700 "$NH_LAUNCHER"
+    if [ -L "${NH_SHORTCUT}" ]; then
+        rm -f "${NH_SHORTCUT}"
     fi
-    if [ ! -f ${NH_SHORTCUT} ]; then
-        ln -s ${NH_LAUNCHER} ${NH_SHORTCUT} >/dev/null
+    if [ ! -f "${NH_SHORTCUT}" ]; then
+        ln -s "${NH_LAUNCHER}" "${NH_SHORTCUT}" >/dev/null
     fi
    
 }
 
+function check_kex() {
+    if [ "$wimg" = "nano" ] || [ "$wimg" = "minimal" ]; then
+        nh sudo apt update && nh sudo apt install -y tightvncserver kali-desktop-xfce
+    fi
+}
 function create_kex_launcher() {
     KEX_LAUNCHER=${CHROOT}/usr/bin/kex
     cat > $KEX_LAUNCHER <<- EOF
@@ -242,7 +311,7 @@ function start-kex() {
     else
         SCREEN=":1"
     fi 
-    export HOME=\${HOME}; export USER=\${USR}; LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgcc_s.so.1 nohup vncserver \$SCREEN >/dev/null 2>&1 </dev/null
+    export MOZ_FAKE_NO_SANDBOX=1; export HOME=\${HOME}; export USER=\${USR}; LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgcc_s.so.1 nohup vncserver \$SCREEN >/dev/null 2>&1 </dev/null
     starting_kex=1
     return 0
 }
@@ -310,11 +379,17 @@ function fix_profile_bash() {
     fi
 }
 
+function fix_resolv_conf() {
+    ## We don't have systemd so let's use static entries for Quad9 DNS servers
+    echo "nameserver 9.9.9.9" > $CHROOT/etc/resolv.conf
+    echo "nameserver 149.112.112.112" >> $CHROOT/etc/resolv.conf
+}
+
 function fix_sudo() {
     ## fix sudo & su on start
     chmod +s $CHROOT/usr/bin/sudo
     chmod +s $CHROOT/usr/bin/su
-	echo "kali    ALL=(ALL:ALL) ALL" > $CHROOT/etc/sudoers.d/kali
+    echo "kali    ALL=(ALL:ALL) ALL" > $CHROOT/etc/sudoers.d/kali
 
     # https://bugzilla.redhat.com/show_bug.cgi?id=1773148
     echo "Set disable_coredump false" > $CHROOT/etc/sudo.conf
@@ -324,8 +399,8 @@ function fix_uid() {
     ## Change kali uid and gid to match that of the termux user
     USRID=$(id -u)
     GRPID=$(id -g)
-    nh -r usermod -u $USRID kali 2>/dev/null
-    nh -r groupmod -g $GRPID kali 2>/dev/null
+    nh -r usermod -u "$USRID" kali 2>/dev/null
+    nh -r groupmod -g "$GRPID" kali 2>/dev/null
 }
 
 function print_banner() {
@@ -344,6 +419,7 @@ function print_banner() {
     printf "${blue}####  ############# NetHunter ####################${reset}\n\n"
 }
 
+
 ##################################
 ##              Main            ##
 
@@ -355,15 +431,7 @@ blue='\033[1;34m'
 light_cyan='\033[1;96m'
 reset='\033[0m'
 
-EXTRA_ARGS=""
-if [[ ! -z $1 ]]; then
-    EXTRA_ARGS=$1
-    if [[ $EXTRA_ARGS != "--no-check-certificate" ]]; then
-        EXTRA_ARGS=""
-    fi
-fi
-
-cd $HOME
+cd "$HOME"
 print_banner
 get_arch
 set_strings
@@ -371,14 +439,15 @@ prepare_fs
 check_dependencies
 get_rootfs
 get_sha
-verify_sha
 extract_rootfs
 create_launcher
 cleanup
 
 printf "\n${blue}[*] Configuring NetHunter for Termux ...\n"
 fix_profile_bash
+fix_resolv_conf
 fix_sudo
+check_kex
 create_kex_launcher
 fix_uid
 
